### ISSUE TITLE
** (FunctionClauseError) no function clause matching in Mailman.Render.normalize_addresses/1

### ISSUE THREAD

**Issue by hudson2010** [mailman-elixir/mailman#89]
hey mailman is crashing 
** (FunctionClauseError) no function clause matching in Mailman.Render.normalize_addresses/1
(mailman 0.4.2) lib/mailman/render.ex:151: Mailman.Render.normalize_addresses("hkisitu@gmail.com")
        (mailman 0.4.2) lib/mailman/render.ex:131: Mailman.Render.headers_for/1
        (mailman 0.4.2) lib/mailman/render.ex:18: Mailman.Render.nest_parts/3
        (mailman 0.4.2) lib/mailman/render.ex:8: Mailman.Render.render/3
        (mailman 0.4.2) lib/mailman.ex:43: Mailman.deliver/3

**Comment by hudson2010** [comment]
Please ignore , I have seen the issue , when sending mail , Mailman expects list of mails for to address
